const data = [
  {
    name: "Volkswagen Tiguan",
    year: "2019",
    distance: "19,855 km",
    transmission: "Automatic",
    fuel: "Diesel",
    price: "$34,888",
    isNew: false,
    sold: false,
  },
  {
    name: "Toyota Highlander XLE",
    year: "2014",
    distance: "69,000 km",
    transmission: "Automatic",
    fuel: "Gas",
    price: "$27,875",
    isNew: true,
    sold: false,
  },
  {
    name: "Lexus RX 350 LUXURY",
    year: "2017",
    distance: "39,850 km",
    transmission: "Automatic",
    fuel: "Gas",
    price: "$38,775",
    isNew: false,
    sold: false,
  },
  {
    name: "Toyota Highlander LE A...",
    year: "2016",
    distance: "104,000 km",
    transmission: "Automatic",
    fuel: "Gas",
    price: "$23,728",
    isNew: false,
    sold: false,
  },
  {
    name: "Hyundai Elantra",
    year: "2017",
    distance: "95,000  km",
    transmission: "Automatic",
    fuel: "Gas",
    price: "$11,788",
    isNew: false,
    sold: false,
  },
  {
    name: "Mercedes-Benz GLE-Cl...",
    year: "2016",
    distance: "59,800 km",
    transmission: "Automatic",
    fuel: "Diesel",
    price: "$38,878",
    isNew: false,
    sold: false,
  },
  {
    name: "Toyota Venza AWD XLE...",
    year: "2015",
    distance: "99,000 km",
    transmission: "Automatic",
    fuel: "Gas",
    price: "$18,620",
    isNew: false,
    sold: true,
  },
  {
    name: "Lexus RX 350 F-SPORT",
    year: "2016",
    distance: "86,000 km",
    transmission: "Automatic",
    fuel: "Gas",
    price: "$34,888",
    isNew: true,
    sold: false,
  },
  {
    name: "Volkswagen Tiguan",
    year: "2019",
    distance: "$34,888",
    transmission: "Automatic",
    fuel: "Diesel",
    price: "19,855 km",
    isNew: false,
    sold: false,
  },
  {
    name: "Toyota Highlander XLE",
    year: "2014",
    distance: "69,000 km",
    transmission: "Automatic",
    fuel: "Gas",
    price: "$27,875",
    isNew: false,
    sold: false,
  },
  {
    name: "Lexus RX 350 LUXURY",
    year: "2017",
    distance: "86,000 km",
    transmission: "Automatic",
    fuel: "Gas",
    price: "$38,775",
    isNew: false,
    sold: false,
  },
  {
    name: "Toyota Highlander LE A...",
    year: "2016",
    distance: "104,000 km",
    transmission: "Automatic",
    fuel: "Gas",
    price: "$23,728",
    isNew: false,
    sold: false,
  },
  {
    name: "Volkswagen Tiguan",
    year: "2019",
    distance: "19,855 km",
    transmission: "Automatic",
    fuel: "Diesel",
    price: "$34,888",
    isNew: true,
    sold: false,
  },
  {
    name: "Toyota Highlander XLE",
    year: "2014",
    distance: "69,000 km",
    transmission: "Automatic",
    fuel: "Gas",
    price: "$27,875",
    isNew: false,
    sold: false,
  },
  {
    name: "Lexus RX 350 LUXURY",
    year: "2017",
    distance: "39,850 km",
    transmission: "Automatic",
    fuel: "Gas",
    price: "39,850 km",
    isNew: false,
    sold: false,
  },
  {
    name: "Toyota Highlander LE A...",
    year: "2016",
    distance: "104,000 km",
    transmission: "Automatic",
    fuel: "Gas",
    price: "$23,728",
    isNew: false,
    sold: false,
  },
  {
    name: "Hyundai Elantra",
    year: "2017",
    distance: "95,000  km",
    transmission: "Automatic",
    fuel: "Gas",
    price: "$11,788",
    isNew: false,
    sold: false,
  },
  {
    name: "Mercedes-Benz GLE-Cl...",
    year: "2016",
    distance: "59,800 km",
    transmission: "Automatic",
    fuel: "Diesel",
    price: "$38,878",
    isNew: false,
    sold: false,
  },
  {
    name: "Toyota Venza AWD XLE...",
    year: "2015",
    distance: "99,000 km",
    transmission: "Automatic",
    fuel: "Gas",
    price: "$18,620",
    isNew: false,
    sold: false,
  },
  {
    name: "Lexus RX 350 F-SPORT",
    year: "2016",
    distance: "86,000 km",
    transmission: "Automatic",
    fuel: "Gas",
    price: "$34,888",
    isNew: true,
    sold: false,
  },
  {
    name: "Volkswagen Tiguan",
    year: "2019",
    distance: "19,855 km",
    transmission: "Automatic",
    fuel: "Diesel",
    price: "$34,888",
    isNew: false,
    sold: false,
  },
  {
    name: "Toyota Highlander XLE",
    year: "2014",
    distance: "69,000 km",
    transmission: "Automatic",
    fuel: "Gas",
    price: "$27,875",
    isNew: false,
    sold: false,
  },
];

export default data;
